reviewers:
  defaults:
    - sineto_meli
  groups:
    visa-clearing:
      - silvioubaldino
      - sineto_meli
      - vitorlichoti

options:
  number_of_reviewers: 1

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
