version: "3.9"

services:
  pg-personal-finance:
    container_name: pg-personal-finance
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ../postgres/.data:/data/postgres
    ports:
      - 5432:5432