package usecase

import "errors"

var (
	ErrDateRequired                  = errors.New("date must be informed")
	ErrMovementAlreadyPaid           = errors.New("movement already paid")
	ErrMovementNotPaid               = errors.New("movement is not paid")
	ErrCreditMovementShouldNotBePaid = errors.New("credit movement should not be paid")
	ErrInsufficientBalance           = errors.New("wallet has insufficient balance")
	ErrInsufficientCreditLimit       = errors.New("credit card has insufficient credit limit")
	ErrInvoiceAlreadyPaid            = errors.New("invoice already paid")
	ErrInvoiceNotPaid                = errors.New("invoice is not paid")
	ErrInvoiceCannotModify           = errors.New("cannot modify movements for paid invoice")
	ErrInvoiceNotFound               = errors.New("invoice not found")
	ErrInvalidClosingDay             = errors.New("closing day must be between 1 and 31")
	ErrInvalidDueDay                 = errors.New("due day must be between 1 and 31")
	ErrInvalidCreditLimit            = errors.New("credit limit must be positive")
	ErrInvalidColor                  = errors.New("invalid color format")
	ErrCreditCardPay                 = errors.New("credit card should`n be paid")
	ErrUnsupportedMovementTypeV2     = errors.New("unsupported movement type for V2 endpoint")
	ErrInvalidPaymentAmount          = errors.New("payment amount must be between invoice amount and zero")
	ErrSameWalletTransfer            = errors.New("origin and destination wallets must be different")
	ErrInvalidTransferAmount         = errors.New("transfer amount must be positive")
	ErrLanguageRequired              = errors.New("language is required")
	ErrInvalidLanguageFormat         = errors.New("language must be in BCP47 format")
	ErrCurrencyRequired              = errors.New("currency is required")
	ErrInvalidCurrencyFormat         = errors.New("currency must be ISO 4217 format")
	ErrTermVersionRequired           = errors.New("term_version is required")
	ErrEmptyToken                    = errors.New("token is empty")
	ErrInvalidPlatform               = errors.New("invalid platform")

	ErrUnauthorized           = errors.New("unauthorized")
	ErrForbidden              = errors.New("forbidden")
	ErrWalletLimitReached     = errors.New("wallet limit reached for your plan")
	ErrCreditCardLimitReached = errors.New("credit card limit reached for your plan")
	ErrMovementLimitReached   = errors.New("movement limit reached for your plan this month")
	ErrRecurrenceLimitReached = errors.New("recurrence limit reached for your plan this month")
	ErrInvalidPlan            = errors.New("invalid plan")
	ErrInvalidRole            = errors.New("invalid role")

	ErrInvalidWebhookSignature  = errors.New("invalid webhook signature")
	ErrMercadoPagoGateway       = errors.New("mercado pago gateway error")
	ErrRevenueCatWebhook        = errors.New("revenuecat webhook error")
	ErrSubscriptionPlanNotFound = errors.New("subscription plan not found")
)
